FROM golang:1.23.2-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /bin/consumer ./cmd/consumer

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /bin/consumer /usr/local/bin/consumer
ENTRYPOINT ["/usr/local/bin/consumer"]
