apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-config
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
data:
  MQ_HOST: "{{ include "telemetry-platform.msgQueueFullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  MQ_PORT: "{{ .Values.queue.port }}"
  MQ_TOPIC: "{{ .Values.queue.topic }}"
  MQ_PARTITION: "{{ .Values.queue.partition }}"
  MQ_SERVER: "{{ include "telemetry-platform.msgQueueFullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.queue.port }}"
  APP_DB_HOST: {{ printf "%s-postgresql" .Release.Name }}
  APP_DB_PORT: "5432"
  APP_DB_NAME: {{ .Values.postgresql.auth.database | quote }}
