{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-api
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry-pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telemetry-pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ default (include "telemetry-pipeline.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "telemetry-pipeline.fullname" . }}-config
            - secretRef:
                name: {{ include "telemetry-pipeline.fullname" . }}-db
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
{{- end }}
