{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-consumer
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry-pipeline.name" . }}
      app.kubernetes.io/component: consumer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telemetry-pipeline.name" . }}
        app.kubernetes.io/component: consumer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "telemetry-pipeline.fullname" . }}-config
            - secretRef:
                name: {{ include "telemetry-pipeline.fullname" . }}-db
          env:
            - name: GROUP_ID
              value: "{{ .Values.consumer.groupId }}"
            - name: POLL_MAX_MESSAGES
              value: "{{ .Values.consumer.poll.maxMessages }}"
            - name: POLL_WAIT_MS
              value: "{{ .Values.consumer.poll.waitMs }}"
            {{- range .Values.consumer.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.consumer.resources | nindent 12 }}
{{- end }}
