{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-migrations
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telemetry-pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres:15-alpine
          command: ["/bin/sh","-c"]
          args:
            - >
              set -euo pipefail;
              echo "==> Connecting to ${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME} as ${APP_DB_USER}";
              for f in /migrations/*.sql; do
                echo "==> Running ${f}";
                PGPASSWORD="${APP_DB_PASSWORD}" psql \
                  -h "${APP_DB_HOST}" -p "${APP_DB_PORT}" -U "${APP_DB_USER}" -d "${APP_DB_NAME}" \
                  -v ON_ERROR_STOP=1 -f "${f}";
              done;
          env:
            - name: APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "telemetry-pipeline.fullname" . }}-config
                  key: APP_DB_HOST
            - name: APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "telemetry-pipeline.fullname" . }}-config
                  key: APP_DB_PORT
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "telemetry-pipeline.fullname" . }}-config
                  key: APP_DB_NAME
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "telemetry-pipeline.fullname" . }}-db
                  key: APP_DB_USER
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "telemetry-pipeline.fullname" . }}-db
                  key: APP_DB_PASSWORD
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: {{ include "telemetry-pipeline.fullname" . }}-migrations
{{- end }}
