{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-api
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "telemetry-pipeline.name" . }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
