# telemetry-pipeline/values.yaml

# Common app settings
image:
  pullPolicy: IfNotPresent

producer:
  enabled: true
  image:
    repository: telemetry-pipeline/producer
    tag: v4-test
  csv:
    pvc:
      enabled: true
      size: 1Gi
      accessModes: ["ReadWriteOnce"]
    filename: "/data/input.csv"
  topic: "gpu-telemetry"
  partition: -1
  readIntervalSeconds: 60

consumer:
  enabled: true
  replicas: 1
  image:
    repository: telemetry-pipeline/consumer
    tag: v4-test
  groupId: "telemetry-consumers"
  topic: "gpu-telemetry"
  partition: -1
  poll:
    maxMessages: 100
    waitMs: 500
  env: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

api:
  enabled: true
  replicas: 1
  image:
    repository: telemetry-pipeline/apiserver
    tag: v4-test
  service:
    type: ClusterIP
    port: 8080
  env: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

queue:
  port: 9092
  topic: "events"


# DB connection details (used by consumer + API)
db:
  host: telemetry-pipeline-postgres
  port: 5432
  name: telemetry
  user: telemetry
  password: telemetry

migrations:
  enabled: true

postgresql:
  primary:
    persistence:
      enabled: true
      size: 10Gi
  auth:
    username: telemetry
    password: telemetry123
    database: telemetry

