apiVersion: v2
name: telemetry-platform
description: Umbrella chart for telemetry platform (msg-queue + pipeline + db)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: msg-queue
    version: 0.1.0
    repository: "file://../msg-queue"   # or use OCI registry / chart repo
  - name: telemetry-pipeline
    version: 0.1.0
    repository: "file://../telemetry-pipeline"
