server:
  nodeId: "node-b"
  grpcAddr: "127.0.0.1:9093"
  httpAddr: "127.0.0.1:8081"
  grpcAdvertisedAddr: "127.0.0.1:9093"


storage:
  dataDir: "./data/node-b"
  segmentBytes: 134217728

replication:
  rf: 3
  quorumAcks: 2

etcd:
  endpoints: ["127.0.0.1:2379"]
  username: ""
  password: ""
  tls:
    enabled: false
