server:
  nodeId: "node-c"
  grpcAddr: "127.0.0.1:9094"
  httpAddr: "127.0.0.1:8082"
  grpcAdvertisedAddr: "127.0.0.1:9094"


storage:
  dataDir: "./data/node-c"
  segmentBytes: 134217728

replication:
  rf: 3
  quorumAcks: 2

etcd:
  endpoints: ["127.0.0.1:2379"]
  username: ""
  password: ""
  tls:
    enabled: false
