replicaCount: 3
image:
  repository: jayabal92/msg-queue
  tag: v1-test
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: ""
service:
  type: ClusterIP
  port: 9092
pdb:
  enabled: true
  minAvailable: 2
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
# storage
persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

replication:
  quorumAcks: 2
  rf: 3

storage:
  segmentBytes: 134217728


etcd:
  replicaCount: 3
  auth:
    rbac:
      enabled: true
      create: true
      allowNoneAuthentication: false
    token:
      enabled: true
    rootPassword: "secret_pass"
  persistence:
    enabled: true
    size: 10Gi
# extra env
extraEnv: []
# e.g.
# extraEnv:
#   - name: GODEBUG
#     value: madvdontneed=1